CREATE TABLE IF NOT EXISTS user_invitations (
  id CHAR(36) PRIMARY KEY,
  clinic_id CHAR(36) NOT NULL,
  email VARCHAR(160) NOT NULL,
  full_name VARCHAR(120) NOT NULL,
  phone VARCHAR(20) NULL,
  role ENUM('CLINIC_OWNER','DOCTOR','RECEPTIONIST','PATIENT') NOT NULL,
  permissions JSON NOT NULL,
  token_hash CHAR(64) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  accepted_at DATETIME(3) NULL,
  revoked_at DATETIME(3) NULL,
  invited_by CHAR(36) NOT NULL,
  created_by CHAR(36) NULL,
  updated_by CHAR(36) NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_user_invitation_token (token_hash),
  KEY idx_user_invitation_tenant_email (clinic_id, email, expires_at, is_deleted),
  KEY idx_user_invitation_pending (clinic_id, accepted_at, revoked_at, expires_at, is_deleted),
  CONSTRAINT fk_user_invitation_clinic FOREIGN KEY (clinic_id) REFERENCES clinics(id),
  CONSTRAINT fk_user_invitation_actor FOREIGN KEY (invited_by) REFERENCES users(id)
);
