/**
 * Permission Constants
 * Defines granular platform permissions.
 */

const PERMISSIONS = Object.freeze({
  CLINICS_MANAGE: 'clinics:manage',
  USERS_MANAGE: 'users:manage',
  PATIENTS_READ: 'patients:read',
  PATIENTS_WRITE: 'patients:write',
  APPOINTMENTS_READ: 'appointments:read',
  APPOINTMENTS_WRITE: 'appointments:write',
  QUEUE_MANAGE: 'queue:manage',
  CLINICAL_READ: 'clinical:read',
  CLINICAL_WRITE: 'clinical:write',
  PRESCRIPTIONS_MANAGE: 'prescriptions:manage',
  LAB_MANAGE: 'lab:manage',
  BILLING_MANAGE: 'billing:manage',
  STORAGE_MANAGE: 'storage:manage',
  WHATSAPP_MANAGE: 'whatsapp:manage',
  NOTIFICATIONS_MANAGE: 'notifications:manage',
  REPORTS_READ: 'reports:read',
  SETTINGS_MANAGE: 'settings:manage',
  SUBSCRIPTIONS_MANAGE: 'subscriptions:manage',
  AUDIT_READ: 'audit:read',
});

const DEFAULT_ROLE_PERMISSIONS = Object.freeze({
  SUPER_ADMIN: ['*'],
  CLINIC_OWNER: ['*'],
  DOCTOR: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.PATIENTS_WRITE,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.APPOINTMENTS_WRITE,
    PERMISSIONS.QUEUE_MANAGE,
    PERMISSIONS.CLINICAL_READ,
    PERMISSIONS.CLINICAL_WRITE,
    PERMISSIONS.PRESCRIPTIONS_MANAGE,
    PERMISSIONS.LAB_MANAGE,
    PERMISSIONS.STORAGE_MANAGE,
    PERMISSIONS.REPORTS_READ,
  ],
  RECEPTIONIST: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.PATIENTS_WRITE,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.APPOINTMENTS_WRITE,
    PERMISSIONS.QUEUE_MANAGE,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.STORAGE_MANAGE,
    PERMISSIONS.WHATSAPP_MANAGE,
    PERMISSIONS.NOTIFICATIONS_MANAGE,
    PERMISSIONS.REPORTS_READ,
  ],
  PATIENT: [PERMISSIONS.PATIENTS_READ, PERMISSIONS.APPOINTMENTS_READ],
});

module.exports = { PERMISSIONS, DEFAULT_ROLE_PERMISSIONS };
